server:
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?useSSL=false&createDatabaseIfNotExist=true
    usernamne: root
    password:  root
  jpa:
    hibernate:
      ddl-auto: update